server:
  port: 8080

spring:
  config:
    import:
      - classpath:/resource-local/application-local.yml
      - classpath:/resource-dev/application-dev.yml
  profiles:
    group:
      local: local
      dev: dev