version: "3"

services:
  spring-app:
    image: rookie3912/ip-server:latest
    container_name: spring-app
    restart: always
    env_file:
      - .env
    ports:
      - "8080:8080"

  reverse-proxy:
    image: nginx
    container_name: reverse-proxy
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    ports:
      - "80:80"
    depends_on:
      - spring-app